language: elixir
matrix:
  include:
    - elixir: 1.13.0
      otp_release: 24.0
cache:
  directories:
    - deps
    - _build
notifications:
  slack:
    on_success: :change
    on_failure: :always
    rooms:
      secure: "BaoA06Rdnsmc8IAl7jAaOe+gn5SFXi2q56mPgIOYb6UIlpAUNsigD/d9Sid8G7wtZ+5OFhXsy7bdT3kD7vNBfdCosq25QBmbdP9+b/4fouCIplS2LtezNpSEwmlTBZW1oJZeDJgUDCNQmIu53yO1Hk2CBjo/vPgz2uzzO8zGEjBKtWrCLkQcNldrHNrWoc/luThZ/exzg33ozQepsb70V0UeieZ2RF4DSc7yG8qCkbGIDzwqD+51fzl4GEkX8Q/ZjTeRkN2dozH8fCvm9Lhob+ZbLcZC/t+Z1XFKcPe6FV6sTalKlN6ofnnHFQ0EoHB1E1iWUdWD83iX+xqV00GEWlvLP5RrCOLn/4Zeznca8da2/Yw3Ar9RMFNaY9MPQOs3TsSPwHrJ3h1/fWFgy8QAj/qlmr4+Paj2CTlSkKpfXYK247K1fzd6qFnD2lMquJP9ISgOqYaPwyiOcag6VL0qxE2YcXBRTOiLVy4rpAbNzdn43NTJRwFy4K0AP7HID6sgVMOI2t8dBHZEgu5kCwBb/WHPE4F8gCKzsl3DHlOYJ0kf0d7PDGILdvOZ15kUU5Q3lCeNqLNiOFMJYtlXwVrC3xcLwKQgz5lBdZRfuhTX7yYMNtTClDATxxf1v9Njx8BBZIlVJ6mZzDW9aWnq1SL9HWAzb1oIE6MteTCxzwrIYrQ="
install:
  - mix do local.rebar --force, local.hex --force
  - mix hex.organization auth simplifi --key ${HEX_API_KEY}
  - mix deps.get
script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=test mix compile --warnings-as-errors
  - mix test
  - mix credo --strict
  - mix dialyzer
after_success:
  - .travis/upload.sh
